# Generated by Django 4.2.7 on 2023-12-05 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comment_delete_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
